server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
    url: jdbc:${POSTGRES_URL}/themusicstore
    username: ${POSTGRES_USERNAME}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin