version: '3.1'
services:
  app:
    container_name: app-spring
    image: app-springboot
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  rental-app:
    container_name: rental-app
    image: rental-app-spring
    build: ../rental
    ports:
      - "8081:8080"
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=themusicstore